### ISSUE TITLE
Per-domain problem categories

### ISSUE THREAD

**Issue by iceb0y** [vijos/vj4#163]

**Comment by breeswish** [comment]
Disagree. Category is used to clearly classify and organize problems among all domains. Allow customizing category is as worse as letting users use customized tags to organize.

**Comment by breeswish** [comment]
If there are categories that VJ4 doesn't support, an issue should be opened.

**Comment by iceb0y** [comment]
Example: https://vijos.org/d/beginning_c_cpp/p

**Comment by breeswish** [comment]
Using category outside our provided list should be rejected.

**Comment by breeswish** [comment]
Close.
