### ISSUE TITLE
How to manage the order?

### ISSUE THREAD

**Issue by SkyLionel** [vijos/vj4#176]
We can see there are too many problems both in codes and management.
Look at this url:https://vijos.org/p/1050/solution
We can set allow some of people who have applied by the MOD of the vijos to delete them and take notes.
**It's important to set some rules to give users the more comfortable environment.**

**Comment by twd2** [comment]
You can down vote these rubbishes.

**Comment by breeswish** [comment]
Please give down-votes to those low quality solutions and they will appear at bottom later.
