### ISSUE TITLE
Highlighter doesn't support line wrap

### ISSUE THREAD

**Issue by ksyx** [vijos/vj4#239]
I think the maximum line number is too small for some complex problems.
See the code at [here](https://vijos.org/records/59706d3ad3d8a119d1da6e43).
I have also took a screenshot: 
![Screenshot](https://miao.su/images/2017/07/21/Screenshotfrom2017-07-2113-25-42e1325.png)

**Comment by q234rty** [comment]
It seems that this is caused by auto breaking long lines.
The number 150 isn't special.

**Comment by ksyx** [comment]
@q234rty
So there is a new issue. The line number doesn't match the actual line number.

**Comment by breeswish** [comment]
@ksyx Yes. This is the actual issue here.
