### ISSUE TITLE
The config of column width in the judge queue is not good

### ISSUE THREAD

**Issue by ksyx** [vijos/vj4#247]
The column *Problem* is too long and columns of time and memory costed is too narrow.

![image](https://user-images.githubusercontent.com/18738953/28715855-b4440f9c-73cc-11e7-8e0a-34c453e0c0f9.png)

**Comment by breeswish** [comment]
These columns are added by @iceb0y in https://github.com/vijos/vj4/commit/2d60ccd32f13d7c22bec2fb6e3b10c2d250f55fc while the page layout was modified later by @twd2 in https://github.com/vijos/vj4/commit/ff39103b7e3111cb187ab8e4ffefb7a58dbabc93

Blame twd2 : )

**Comment by twd2** [comment]
???
