### ISSUE TITLE
Received AC mail of the problem submitted in the contest when a OI-ruled contest is running

### ISSUE THREAD

**Issue by ksyx** [vijos/vj4#258]
![image](https://user-images.githubusercontent.com/18738953/29000208-49eb136c-7a97-11e7-8ef5-dd870aaa9e24.png)
![image](https://user-images.githubusercontent.com/18738953/29000223-876156a2-7a97-11e7-85dc-821142076f85.png)

**Comment by twd2** [comment]
(secret) (You leaked your `sid`.)
