### ISSUE TITLE
How about allow users sort or quit domain which they have joined?

### ISSUE THREAD

**Issue by SkyLionel** [vijos/vj4#288]
Sort the domain which users like.
Quit the domain can help users don't see the unused domain.

**Comment by ksyx** [comment]
How about change *quit* to *hide*? Doing that can be less data loss than *quit*.

**Comment by SkyLionel** [comment]
All right, hide is same as quit.

**Comment by breeswish** [comment]
As previously stated, currently we don't have the concept of "member" and these features won't be considered now. If we are going to implement the member system, those features will be implemented.
