### ISSUE TITLE
Homework System

### ISSUE THREAD

**Issue by breeswish** [vijos/vj4#300]
Homework can be implemented using the contest system, but under the name of "homework" to avoid confusing for users. In addition, in the UI of the homework_main we need to provide a calendar marking the duration of each homework.

- [x] Assignment Creation / Modification
- [x] Assignment Calendar
- [x] Delay Penalty

**Comment by moesoha** [comment]
WIP. #331 #460

**Comment by twd2** [comment]
Done.
