### ISSUE TITLE
Random pid when adding problem via web interface

### ISSUE THREAD

**Issue by dianlujitao** [vijos/vj4#370]
If a problem is added via python command similar to
```bash
pm vj4.model.adaptor.problem add system "Dummy Problem" "# It *works*" -1 1000
```
it has readable pid (1000 in this case)

but adding problems via web interface generates ramdom pids such as ```59d73f3745a5412493c524fc```

Is this a bug? How to workaround this?

**Comment by twd2** [comment]
Not a bug. It's MongoId (aka. ObjectId).

See: #330
