### ISSUE TITLE
Add filter problem by problem name in Judging Queue

### ISSUE THREAD

**Issue by ksyx** [vijos/vj4#388]
Just like input the username and pop out the user list that matches the input.

**Comment by breeswish** [comment]
Judging queue is not intended to be used for this feature. It is only used for inspecting whether the judger is functioning and it may be removed anytime in future. What you expect might be covered by per-problem analytics page, which is already planned but not implemented yet. We are not going to expose the detail of every submission (except admins) for privacy protection consideration.
