### ISSUE TITLE
How to remove a problem or a domain?

### ISSUE THREAD

**Issue by TomXia** [vijos/vj4#390]
I added a problem for testing, and now I don't need it any more. How to remove?
Thanks a lot.

**Comment by ksyx** [comment]
You can't remove that. It doesn't matter.

**Comment by Johnsonsky** [comment]
You can also change it to a new problem :)

**Comment by breeswish** [comment]
Currently we does not support removing a problem because problems are referenced in too many contexts, for example, contest, trainings, etc.

**Comment by TomXia** [comment]
@Wenxuan Shi
Got it. Thanks!
