### ISSUE TITLE
Night mode

### ISSUE THREAD

**Issue by ksyx** [vijos/vj4#395]
Reverse color of the page, it's easy I think...

Effects: 
![image](https://user-images.githubusercontent.com/18738953/33522713-30a59770-d82e-11e7-9517-cbc6964ace5f.png)
![image](https://user-images.githubusercontent.com/18738953/33522715-4eea0fe0-d82e-11e7-982e-2eeff24b3acc.png)
![image](https://user-images.githubusercontent.com/18738953/33522719-61530cc2-d82e-11e7-8dad-dd3605a3343c.png)
![image](https://user-images.githubusercontent.com/18738953/33522732-8aac4d54-d82e-11e7-9d7f-599b4e2e6ff7.png)
![image](https://user-images.githubusercontent.com/18738953/33522734-9a841018-d82e-11e7-869e-1b20f4e4f0ef.png)
![image](https://user-images.githubusercontent.com/18738953/33522737-ac55e3fc-d82e-11e7-8703-c57e8c1e8c0d.png)

**Comment by breeswish** [comment]
Its ugly though....

**Comment by Johnsonsky** [comment]
duplicate with #384 ?

**Comment by Johnsonsky** [comment]
That's cool...
233

**Comment by ksyx** [comment]
emmmmm... but it's the easiest way to have a night mode and it's acceptable I think..

**Comment by twd2** [comment]
duplicate with #384, closing
