### ISSUE TITLE
More ways to judge

### ISSUE THREAD

**Issue by BillYang2016** [vijos/vj4#399]
This issue is opened long time ago,but hasn't been regarded.
Not only special judge required,but also submit answer & interactive problems are important.
Though Traditional problems are important,we can frequently see new submit answer & interactive problems on many contests,they are more welcomed.
However,I don't have the ability to submit a PR too,sorry for that.
#387

**Comment by ksyx** [comment]
#397

**Comment by q234rty** [comment]
For sumbit answer problems:vijos/jd4#42

**Comment by BillYang2016** [comment]
so special judge & interactive problems should be regarded seriously?

**Comment by twd2** [comment]
secret

**Comment by zzhou612** [comment]
So how can I add a special judge problem? Is the "special judge" feature available in the master branch?
