### ISSUE TITLE
自己安装vijos的3个问题

### ISSUE THREAD

**Issue by 1046329594** [vijos/vj4#409]
1.如何修改备案号？
2.如何配置多评测机？
3.如何修改默认域（Vijos）？

**Comment by breeswish** [comment]
1. You need to modify [builtin.py](https://github.com/vijos/vj4/blob/79ae6bf4ae492c066b48f0cbf9aac82c52197bfa/vj4/model/builtin.py#L309)
2. Just start multiple judges.
3. Still, please take a look at `builtin.py`.

**Comment by 1046329594** [comment]
close

**Comment by 1046329594** [comment]
How many judge users will I need?

**Comment by 1046329594** [comment]
How many judge users will I need?

**Comment by twd2** [comment]
At least 1. We suggest the number of judges.

**Comment by 1046329594** [comment]
Alright.
