### ISSUE TITLE
A request of APIs in Vijos

### ISSUE THREAD

**Issue by ksyx** [vijos/vj4#412]
In that order, we can support more functions using more programming languages.

**Comment by ksyx** [comment]
We can open it for **trusted** users and vaildate API permissions using something like *secret* and *API Key*

**Comment by iceb0y** [comment]
I didn't fully understand the request. New programming languages can be easily added, for example c7e76175160aad1720a1b1a19d04f685e1a1d2cf and vijos/jd4@95b5ed525d3e6af85fbe9f24ff9e42deb005be93 adds ruby support.

**Comment by ksyx** [comment]
That isn't my point. Vijos was developd by Python. We can develop Vijos with more programming language if we have a document of Vijos APIs. Such as, we can support more types of problems. An example sense is, user uploaded a problem to vijos, then he made a program using his API keys. We know that Vijos do not support interation problems, and he used the program to have intercations with another user's program. After intercations,  the program submited the result with parameters: *user's sessionid, API keys, verdict, problemid, domain*. After receving these information, Vijos will create a judging record, just like the program is a judger and judged a problem.

**Comment by iceb0y** [comment]
Problems with custom judge are supported by our secret internal interface. An example can be found at https://github.com/vijos/jd4/blob/master/jd4/testdata/decompose-sum.zip . The custom judge can be written in any supported language.

**Comment by ksyx** [comment]
Wow, that's awsome!

**Comment by twd2** [comment]
secret
