### ISSUE TITLE
run webpack failed

### ISSUE THREAD

**Issue by yanzmgit** [vijos/vj4#416]
[root@yan build]# npm run build

> vj4@4.0.0 build /root/downloads/yan/vj4
> node scripts/build

[07:04:17] Starting task: iconfont
[07:04:18] Starting task: constant
[07:04:18] Starting task: locale
[07:04:18] Finished: locale
[07:04:18] Finished: constant
[07:04:18] gulp-svgicons2svgfont: Font created
[07:04:18] Starting task: iconfont:template
[07:04:18] Finished: iconfont:template
[07:04:18] Finished: iconfont
[07:04:18] Starting task: default
[07:04:18] Finished: default
 28% building modules 154/275 modules 121 active ...core-js/library/fn/symbol/iterator.jsKilled

EveryTime the error is not the same js file,like
 28% building modules 157/286 modules 129 active ...zm/vj4/node_modules/lodash/_Symbol.jsKilled

I check the webpack.config.js , and not find the reason. My dev env are：
[root@yan build]# node -v
v8.10.0
[root@yan build]# npm -v
5.6.0

could you give some suggestion? thanks。

**Comment by yanzmgit** [comment]
i want to run webpack instead of the runpack. beause it may solve this problem。

**Comment by breeswish** [comment]
It should be an out of memory.

**Comment by breeswish** [comment]
As far as I know, building static assets is indeed costing memory. Actually you can build it elsewhere and copy to the server.. or grab our prebuilt files from the [release](https://github.com/vijos/vj4/releases).

**Comment by yanzmgit** [comment]
Thanks @breeswish

I checked my server， yes， it is small  of only 512 M.

For now I choose the  last way to grab prebuilt files from the release and succeed.

Later I wil use a new server , and will report the result  ASP.
