### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by twd2** [vijos/vj4#427]
like aiohttp 3.0+, sockjs, ...

**Comment by iceb0y** [comment]
We can re-evaluate pypy3 performance and compatibility.

**Comment by iceb0y** [comment]
With empty database and 1 process:

* CPython 3.5.3 yields ~500 qps/core with 70 MB RSS.
* PyPy3.5 v6.0, when warmed up, yields ~1200 qps/core with 211 MB RSS.

We should use pypy when we get more memory :)

**Comment by iceb0y** [comment]
https://vijos.org is using PyPy3.5 v6.0, prefork, `aiohttp==3.4.4`, `sockjs==0.9.1`.

We are testing in production :smiley:

**Comment by iceb0y** [comment]
Note: in production environment however, pypy yields 170 qps, and cpython yields 290 qps.
