### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by iceb0y** [vijos/vj4#451]
We notice a 80MB/(day*process) memory leak on vijos.org.

We suspect it comes from new versions of dependencies.

We currently use kill-and-restart to keep it running:

* `0 6 * * * systemctl restart vj4`

General ways to solve python memory leak:

* https://mg.pov.lt/objgraph/
* https://github.com/aaiyer/rfoo
* `[*map(asyncio.Task.print_stack, asyncio.Task.all_tasks())]`

**Comment by twd2** [comment]
Why is feature label added???

**Comment by iceb0y** [comment]
After running for a while

```
builtins.dict 29445
builtins.function 14812
builtins.tuple 8920
builtins.list 8632
builtins.weakref 6389
functools.partial 5634
collections.deque 4371
bson.int64.Int64 3694
builtins.cell 2367
bson.objectid.ObjectId 2326
builtins.set 2294
builtins.coroutine 2057
_asyncio.Task 1940
multidict._multidict.CIMultiDict 1885
urllib.parse.SplitResult 1881
http.cookies.SimpleCookie 1881
yarl.URL 1878
aiohttp.web_response.Response 1878
builtins.mappingproxy 1877
aiohttp._http_parser.RawRequestMessage 1876
multidict._multidict.CIMultiDictProxy 1875
aiohttp.http_writer.StreamWriter 1875
aiohttp.web_request.Request 1875
aiohttp.web_urldispatcher.UrlMappingMatchInfo 1875
aiohttp.web_protocol.RequestHandler 1827
builtins.type 1812
socket.socket 1792
asyncio.selector_events._SelectorSocketTransport 1788
vj4.handler.record.RecordDetailConnection 1612
builtins.getset_descriptor 1550
asyncio.events.TimerHandle 1406
builtins.wrapper_descriptor 1337
```

And there are many live coroutines with no frames.

**Comment by iceb0y** [comment]
![leak](https://raw.githubusercontent.com/gist/iceb0y/12fbd0680be57627e532d084d37ded9e/raw/c37d074c2080ef45100897f520a9e9997bc21d61/leak.svg?sanitize=true)
