### ISSUE TITLE
Copy Problem

### ISSUE THREAD

**Issue by twd2** [vijos/vj4#475]
- [x] data reference
- [x] problem copy
- [x] initiate from source problem detail page
- [x] initiate batch copy from destination domain
- [x] Counter for being copied times

**Comment by moesoha** [comment]
Add a page for copying problems from specific domain.

Copy contents and tags.

User who perform this action requires view permission from source domain and create permission from destination domain.

Add ` > Copied from domain/pid.` to content.

Data reference is also set to source domain. Avoiding stealing data.

**Comment by twd2** [comment]
Considering add a copy count for each problem showing which problem is hot.

**Comment by wlnirvana** [comment]
Any ETA for this feature (even without the copied count)?

**Comment by moesoha** [comment]
This feature is marked as "priority/P0", that means we will work on this issue first once we have free time. Our school which uses vj4 as well is also requesting this feature. Although there isn't any ETA, this feature will be available in 2 or 3 months.On Mar 6, 2019 9:21 AM, wlnirvana <notifications@github.com> wrote:Any ETA for this feature (even without the copied count)?

**Comment by moesoha** [comment]
Working at #495

**Comment by moesoha** [comment]
#495 merged.
