### ISSUE TITLE
Can domain managers (coaches) view the submission details?

### ISSUE THREAD

**Issue by wlnirvana** [vijos/vj4#485]
For a specific problem, as a domain manager I am wondering if it is possible to see:

1. A list of all the submissions (sorted by time for example)
2. The user ID for each submission
3. The source code of each submission
4. The status for each submission
5. The output (or the diff) for the failed submissions

**Comment by breeswish** [comment]
Currently it is available for contests and homeworks, but not (directly) available for normal problems.

**Comment by wlnirvana** [comment]
It seems possible to view the source code of a submission, but not the output diff. Is the output persisted at all?

**Comment by twd2** [comment]
We do not store the output at this time. You can feel free to modify the jd4 and vj4 to support this and propose a PR.

**Comment by wlnirvana** [comment]
Thanks for the clarification!
