### ISSUE TITLE
Homework total time calculation incorrect

### ISSUE THREAD

**Issue by wlnirvana** [vijos/vj4#490]
![image](https://user-images.githubusercontent.com/3822785/54690641-ca9ef400-4b5c-11e9-8d8d-62c651c90ccb.png)

I did three submissions around 21:47, in <1min. But the total time consumed is 1h+.

I suppose the number now is just a simple sum over the submission times of all the problems in that homework?

**Comment by wlnirvana** [comment]
I suddenly came to realization that each submission time is calculated as an offset from the starting time of that homework? Now the total time column begins to make sense to me.

Though I still think this is not very reasonable (as one may well work only part-time, or start the next problem only after the previous one gets AC), please feel free to close this issue.

**Comment by twd2** [comment]
@breeswish PTAL

**Comment by breeswish** [comment]
That should be an expected behaviour, because we actually have no way to precisely know when user started to work on a single problem.
