### ISSUE TITLE
Ban user

### ISSUE THREAD

**Issue by masnn** [vijos/vj4#491]
I found someone created account on my site and submitted lots of junk codes. 
I want to know if there is a way to view the list of currently registered users and delete/disable some accounts.
And I wonder if there's a way to ban a IP address.

**Comment by masnn** [comment]
I found users can be deleted by editing the database.
But I still don't know how to ban IP address.

**Comment by iceb0y** [comment]
There is an IP blacklist, see vj4/model/blacklist.py and vj4/job/blacklist.py .
