### ISSUE TITLE
tdsourcetag is Really annoying!

### ISSUE THREAD

**Issue by masnn** [vijos/vj4#493]
![image](https://user-images.githubusercontent.com/29992205/55167563-34964980-51ac-11e9-883b-94e5921495ec.png)

Some APP(like QQ,TIM) will add a tdsourcetag to the link.
And it will cause an error.
![image](https://user-images.githubusercontent.com/29992205/55167513-1af50200-51ac-11e9-9f9a-df74a1da90d1.png)

**Comment by twd2** [comment]
Should be fixed by #483, please check.

**Comment by masnn** [comment]
I've updated the docker image.
Now the problem is fixed.
Thanks!
