### ISSUE TITLE
如何添加题目？

### ISSUE THREAD

**Issue by Ruanxingzhi** [vijos/vj4#5]
感谢帮助，内网的vijos服务已经搭建了。

现在的问题是，如何添加题目？在Readme.md中有：
```
pm vj4.controller.problem add system "Dummy Problem" "# It *works*" -1 777
```
这一段话运行成功了，题库中多了一个“Dummy Problem”。

那么我现在需要解决的事情是：
> 添加题目：标题、描述、输入输出等。
> 添加数据。

请问上述问题如何解决？

**Comment by twd2** [comment]
`"Dummy Problem"`改成您的题目标题, 将`"# It *works*"`换成题目的详细内容, 包括“描述、输入输出等”即可添加题目。

添加数据需要执行

```
pm vj4.fs.add_local <path of data package(.zip)>
```

获得一个ObjectId之后, 执行

```
pm vj4.controller.problem set_data <domcain id> <pid> <ObjectId>
```

就可以了。
