### ISSUE TITLE
Failed to call 'afterLoading' of record_detail

### ISSUE THREAD

**Issue by nature-li** [vijos/vj4#534]
I deploy a vijos platform using vijos-docker from https://github.com/vijos/vj4-docker.git and I create a problem. When I submit the answer to the problem, It gives me this error:
############################################
Failed to call 'afterLoading' of record_detail
http://192.168.148.128:8888/vj4.js?c698682eb9:1:77761
c@http://192.168.148.128:8888/vendors.js?30e4cde2af:22:29588
http://192.168.148.128:8888/vendors.js?30e4cde2af:22:29373
n@http://192.168.148.128:8888/vendors.js?30e4cde2af:9:9177
s@http://192.168.148.128:8888/vendors.js?30e4cde2af:9:9388
promiseReactionJob@[native code]
#############################################

What's the problem?

**Comment by moesoha** [comment]
This problem is already fixed in #520 . But I found the code of `vijos/vj4:latest` is behind the repo. You can use `vijos/vj4:debian` or `vijos/vj4:alpine` as a workaround. I'm also building new images based on the latest code, and will notify you when `vijos/vj4:latest` is ready.

**Comment by moesoha** [comment]
Docker images are up to date now.

**Comment by nature-li** [comment]
ok, thanks
