### ISSUE TITLE
Help! How to add a problem from command line

### ISSUE THREAD

**Issue by Philogag** [vijos/vj4#539]
I only found a way to link the data to the problem in the wiki.
I found a `add` function on `vj4.vj4.model.adaptor.problem` but it seens not suitable for command line.
How can I add a problem if I have a markdown file as the problem content.
Or please tell me which function should I use in source code, I will try it by myself.

**Comment by twd2** [comment]
`add` is for adding problems. You can also write a function like `add_file` to add problems loading the contents from files.
