### ISSUE TITLE
mmdb download issue

### ISSUE THREAD

**Issue by masnn** [vijos/vj4#569]
```sh
curl "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz" | gunzip -c > GeoLite2-City.mmdb
```

is no longer working.

**Comment by moesoha** [comment]
ref: https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

**Comment by masnn** [comment]
I know, but README should be changed.

**Comment by moesoha** [comment]
Downloading GeoLite Database requires an account now. We need to update `README.md`.

**Comment by masnn** [comment]
```sh
curl "https://cdn.vijos.org/fs/254b16ee0aff6a0a885b8265964939dffc413fdb" > GeoLite2-City.mmdb
```

:fog:
