### ISSUE TITLE
Remove all attach_xxxs, update_xxxs and unnecessary deepcopy()s

### ISSUE THREAD

**Issue by iceboy-sjtu** [vijos/vj4#59]
We want to make data immutable instead of always copying them.

Use `aiters.to_dict(user.get_multi(_id={'$in': uids}), '_id')` instead of `user.attach_udocs(...)`.

**Comment by twd2** [comment]
Example: https://github.com/vijos/vj4/commit/29d044708c68c879646ca9b305012a017a198a0f
