### ISSUE TITLE
Unable to login, register or find passcode.

### ISSUE THREAD

**Issue by hanbang-wang** [vijos/vj4#65]
![Capture.PNG](https://superfashi.b0.upaiyun.com/wp-content/uploads/2016/08/Capture.png)
![Capture2.PNG](https://superfashi.b0.upaiyun.com/wp-content/uploads/2016/08/Capture2.png)
![Capture3.PNG](https://superfashi.b0.upaiyun.com/wp-content/uploads/2016/08/Capture3.png)

**Comment by twd2** [comment]
@LukeXuan

**Comment by twd2** [comment]
Fixed.
