### ISSUE TITLE
Python code unexpectedly running under high memory usage.

### ISSUE THREAD

**Issue by hanbang-wang** [vijos/vj4#68]
Such simple code to solve *A + B Problem*
```
a, b = [int(i) for i in raw_input().split()]
print(a + b)
```
would cost up to 19 to 20M+ of memory usage, causing Memory Excess (Runtime Error).

Within the previous version of vijos, one code would only cost 4-5M of memory.

This should be either compiler's or statistic's problem.

**Comment by twd2** [comment]
Vj2 uses pypy, but vj4 uses CPython. I think this is the point.

**Comment by hanbang-wang** [comment]
GitHub's email reply system didn't work?

**Comment by iceboy-sjtu** [comment]
That's because they are mad and use pypy as python interpreter. We are currently doing the web part and didn't take seriously for the judge part (the judge running for 4.vijos.org is adapted from jd3, which is the judge using by vj2 for many years).
