### ISSUE TITLE
Move framework logic into an independent repository

### ISSUE THREAD

**Issue by iceb0y** [vijos/vj4#69]
Such as `argmethod`, `options`, colored logger and HTTP router. We can improve reusability, interface, performance (lazy option parser, optimize router and HTTP framework), test coverage.

_unnamed web framework, inspired by vj4_

**Comment by LukeXuan** [comment]
We may focus on this later. I really wish to see it usable before the Christmas :).

**Comment by SummerWish** [comment]
Oh. We invented a framework.
